name: Deploy Backend to Cloud Run (via Docker Hub with unique tag)

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: affable-grin-282703
      REGION: australiaeast1
      SERVICE_NAME: llm-backend
      DOCKERHUB_REPO: kdheeraj/llm-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set unique image tag
        run: echo "IMAGE_TAG=${{ env.DOCKERHUB_REPO }}:$(date +%s)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image with tag ${{ env.IMAGE_TAG }}
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.IMAGE_TAG }}
          no-cache: true

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image docker.io/${{ env.IMAGE_TAG }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --service-account firestore-acc@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
