name: Deploy Backend to Cloud Run (via Docker Hub)

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: affable-grin-282703
      REGION: australiaeast1
      SERVICE_NAME: llm-backend
      DOCKER_IMAGE: yourdockerhubusername/llm-backend  # Change this

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }} ./backend

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.DOCKER_IMAGE }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image docker.io/${{ env.DOCKER_IMAGE }} \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --platform managed \
            --service-account firestore-acc@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
